### ISSUE TITLE
MIE Infrastructure: MIE updates.

### ISSUE THREAD

**Issue by tomgilman** [aburkleaux-amazon/aws-media-insights-engine#36]
As a demo platform, we have not prioritized testing update paths for MIE.  MIE Alpha releases thus far have not been backward compatible.  If for some reason, CloudFormation fails to update when dependencies change, we don’t really have a path that will preserve MIE workflow and asset metadata.  Outputs in S3 will always be preserved.

**Comment by aburkleaux-amazon** [comment]
I tried deleting the MIE stacks layer by layer to see if I can get a successful update of the operator library:

set DeployDemoApp to false and update
set DeployKitchenSinkWorkflow and DeployRekognitionWorkflow to false and update
set DeployOperatorLibrary to false and update

Delete operator library stack failed with one one operator delete failing to resolve within timeout.  Could this be related to #7?

**Comment by tomgilman** [comment]
@brandold

**Comment by aburkleaux-amazon** [comment]
Brandon did some digging on updates… since we always rename the paths to the lambdas on new releases (with the new version), CloudFormation will update the code for all the lambdas.  In our developer builds, we often use the same “version” as we rebuild with our changes, so paths are not updated and CloudFormation doesn’t detect the code changes.  Long story short.  Updates should work from one release to another.
