### ISSUE TITLE
MIE Infrastructure: Block multiple users running workflows on the same asset at the same time

### ISSUE THREAD

**Issue by tomgilman** [aburkleaux-amazon/aws-media-insights-engine#37]
UPDATE: When we add reprocess, i.e. running a new workflow on an existing AssetId, we are adding updates to MIE.  We need to make sure that workflows updating that same AssetId can't run at the same time.  Prior to having reprocess, every workflow created a new Asset in the dataplane, so this was not a porblem.

May need some work. Two reprocess scenarios:
    1. I want to restart the workflow at a specific point and replace the downstream outputs from the previous workflow.  I don’t want to rerun operators that are still good from the last workflow.  My question is whether the workflow_execution_id is a key (rather than an attribute).  Not sure how duplicates from different workflows are resolved by dataplane.  If everything has to come from the same workflow, may be able to get this by passing the previous workflow id and giving to dataplane or even using step function copy/restart of the original workflow.
    2. I want to run a workflow on the same asset but add something I didn’t run before.  For example, a new language translation.  So, all operators would be disabled except the translation.

**Comment by tomgilman** [comment]
Need to validate.

**Comment by aburkleaux-amazon** [comment]
Brandon and I discussed the semantics of this one.  We think the existing reprocess will work for both of these scenarios.  However, we need to add protection to prevent multiple workflows from running on the same asset at the same time.  This is true for the main MIE project as well.  

The new behavior should be as follows:
- If a new workflow starts that is a reprocess (specifies an AssetId rather than a file as input), then the API processing should check (using Consistent Read) the table of running workflows to see if there is currently any running workflow with the same AssetId.
- If a workflow with the same AssetId is found, the /workflow/execution API will return 409 Conflict

**Comment by aburkleaux-amazon** [comment]
Fixed in #63
